export const COMPANY = {
  name: 'SafeCert Skills Ltd',
  tagline: "Get Trained, Get Certified",
  subtitle: "UK's #1 Security Training & Certification Provider",
  phone: '0800 123 4567',
  email: 'info@safecertskills.co.uk',
  address: 'London, United Kingdom',
  trustpilot: {
    rating: 4.9,
    reviews: 12847,
    label: 'Excellent',
  },
  stats: [
    { value: '50,000+', label: 'Students Trained' },
    { value: '120+', label: 'UK Locations' },
    { value: '15+', label: 'Years Experience' },
    { value: '98%', label: 'Pass Rate' },
  ],
}

export const CATEGORIES = [
  { id: 'security', name: 'Security', icon: '🛡️', href: '/courses?cat=security', color: 'from-blue-600 to-blue-800' },
  { id: 'alcohol', name: 'Alcohol', icon: '🍺', href: '/courses?cat=alcohol', color: 'from-amber-500 to-amber-700' },
  { id: 'construction', name: 'Construction', icon: '🔨', href: '/courses?cat=construction', color: 'from-orange-500 to-orange-700' },
  { id: 'firstaid', name: 'First Aid', icon: '🏥', href: '/courses?cat=firstaid', color: 'from-red-500 to-red-700' },
  { id: 'elearning', name: 'E-Learning', icon: '💻', href: '/courses?cat=elearning', color: 'from-purple-500 to-purple-700' },
  { id: 'driving', name: 'Driving', icon: '🚗', href: '/courses?cat=driving', color: 'from-green-500 to-green-700' },
]

export const COURSES = [
  {
    id: 'door-supervisor',
    category: 'security',
    title: 'SIA Door Supervisor Training',
    duration: '6 Weeks',
    price: '£850',
    originalPrice: '£1,100',
    level: 'Level 2 & 3',
    icon: '🚪',
    description: 'Become a fully licensed SIA Door Supervisor. This comprehensive course covers all aspects of security, conflict management, and physical intervention.',
    features: ['SIA Licence Preparation', 'Physical Intervention', 'Conflict Management', 'First Aid Included', 'Job Placement Support'],
    popular: true,
    href: '/courses/door-supervisor',
  },
  {
    id: 'security-guard',
    category: 'security',
    title: 'SIA Security Guard Training',
    duration: '4 Weeks',
    price: '£650',
    originalPrice: '£850',
    level: 'Level 2',
    icon: '👮',
    description: 'Start your career in security. This course covers all the knowledge and skills needed to obtain your SIA Security Guard licence.',
    features: ['SIA Licence Preparation', 'Site Security Management', 'Emergency Procedures', 'Report Writing', 'CCTV Awareness'],
    popular: false,
    href: '/courses/security-guard',
  },
  {
    id: 'cctv',
    category: 'security',
    title: 'SIA CCTV Operator Training',
    duration: '2 Weeks',
    price: '£450',
    originalPrice: '£600',
    level: 'Level 2',
    icon: '📷',
    description: 'Master CCTV surveillance operations. Learn how to monitor, record and manage CCTV systems effectively.',
    features: ['CCTV Operation', 'Data Protection (GDPR)', 'Evidence Handling', 'Control Room Procedures', 'SIA Licence Prep'],
    popular: false,
    href: '/courses/cctv',
  },
  {
    id: 'close-protection',
    category: 'security',
    title: 'Close Protection Training',
    duration: '8 Weeks',
    price: '£2,200',
    originalPrice: '£2,800',
    level: 'Level 3',
    icon: '🕵️',
    description: 'Elite close protection training for those who want to work as bodyguards protecting high-profile individuals.',
    features: ['Threat Assessment', 'Convoy Procedures', 'Surveillance Detection', 'Emergency Driving', 'First Aid Advanced'],
    popular: false,
    href: '/courses/close-protection',
  },
  {
    id: 'personal-licence',
    category: 'alcohol',
    title: 'Personal Licence Training (APLH)',
    duration: '2 Days',
    price: '£350',
    originalPrice: '£450',
    level: 'Level 2',
    icon: '🍺',
    description: 'Obtain your personal licence to sell alcohol. Essential for bar managers, pub owners and hospitality professionals.',
    features: ['Licensing Law', 'Responsible Service', 'DPS Qualification', 'Exam Preparation', 'Online Resources'],
    popular: false,
    href: '/courses/personal-licence',
  },
  {
    id: 'cscs-green',
    category: 'construction',
    title: 'Green CSCS Labourer Card',
    duration: '1 Day',
    price: '£180',
    originalPrice: '£250',
    level: 'Entry Level',
    icon: '🔨',
    description: 'Get your CSCS Green Labourer card and access construction sites across the UK.',
    features: ['Health & Safety', 'Site Induction', 'CITB Test Prep', 'Card Application Help', 'Same Week Results'],
    popular: false,
    href: '/courses/cscs-green',
  },
  {
    id: 'efaw',
    category: 'firstaid',
    title: 'Emergency First Aid at Work',
    duration: '1 Day',
    price: '£120',
    originalPrice: '£160',
    level: 'Level 3',
    icon: '🏥',
    description: 'Gain essential first aid skills for the workplace. Nationally recognised EFAW qualification.',
    features: ['CPR & AED', 'Choking Response', 'Bleeding Control', 'Workplace Scenarios', 'HSE Compliant Certificate'],
    popular: false,
    href: '/courses/efaw',
  },
  {
    id: 'sia-topup-ds',
    category: 'security',
    title: 'SIA Top-Up for Door Supervisors',
    duration: '3-4 Days',
    price: '£290',
    originalPrice: '£380',
    level: 'Refresher',
    icon: '🔄',
    description: 'Renew your Door Supervisor licence with our comprehensive top-up training course.',
    features: ['Licence Renewal', 'Updated Legislation', 'Conflict Management Refresh', 'First Aid Update', 'Flexible Dates'],
    popular: true,
    href: '/courses/sia-topup-ds',
  },
]

export const LICENCES = [
  {
    id: 'door-supervisor-licence',
    title: 'SIA Door Supervisor Licence',
    icon: '🚪',
    description: 'Required to work as a door supervisor at licensed premises such as nightclubs, pubs, and events.',
    steps: ['Complete approved training', 'Pass BTEC exams', 'Apply online via SIA', 'DBS check', 'Receive licence (6-8 weeks)'],
    cost: '£190 (SIA Fee)',
    validity: '3 Years',
    href: '/licences/door-supervisor',
  },
  {
    id: 'security-guard-licence',
    title: 'SIA Security Guard Licence',
    icon: '👮',
    description: 'Required to work as a security guard in any commercial or public setting in the UK.',
    steps: ['Complete Level 2 Award', 'Pass end-point assessment', 'Apply to SIA', 'Identity & DBS check', 'Receive licence'],
    cost: '£190 (SIA Fee)',
    validity: '3 Years',
    href: '/licences/security-guard',
  },
  {
    id: 'cctv-licence',
    title: 'SIA CCTV Licence',
    icon: '📷',
    description: 'Required to operate CCTV in a public space or on behalf of an employer in a private space.',
    steps: ['Complete CCTV training', 'Pass assessment', 'Apply to SIA', 'Background check', 'Receive licence'],
    cost: '£190 (SIA Fee)',
    validity: '3 Years',
    href: '/licences/cctv',
  },
  {
    id: 'close-protection-licence',
    title: 'SIA Close Protection Licence',
    icon: '🕵️',
    description: 'Required to work as a bodyguard or close protection officer in the UK.',
    steps: ['Complete CP training course', 'First aid qualification', 'Apply to SIA', 'Enhanced DBS', 'Receive licence'],
    cost: '£190 (SIA Fee)',
    validity: '3 Years',
    href: '/licences/close-protection',
  },
  {
    id: 'personal-licence',
    title: 'Personal Alcohol Licence',
    icon: '🍺',
    description: 'Required to be the Designated Premises Supervisor (DPS) for any licensed premises selling alcohol.',
    steps: ['Pass APLH qualification', 'Apply to local council', 'DBS check', 'Pay council fee', 'Receive licence'],
    cost: '~£37 (Council Fee)',
    validity: 'Indefinite',
    href: '/licences/personal',
  },
  {
    id: 'cscs-card',
    title: 'CSCS Green Labourer Card',
    icon: '🔨',
    description: 'Allows you to work on construction sites across the UK as a labourer.',
    steps: ['Pass CITB Health & Safety test', 'Complete labourer training', 'Apply for CSCS card', 'Card issued within days'],
    cost: '£36 (CSCS Fee)',
    validity: '5 Years',
    href: '/licences/cscs',
  },
]

export const CAREERS = [
  { title: 'Door Supervisor', salary: '£25,000 – £35,000', category: 'security', icon: '🚪' },
  { title: 'Security Guard', salary: '£20,000 – £28,000', category: 'security', icon: '👮' },
  { title: 'CCTV Operator', salary: '£22,000 – £30,000', category: 'security', icon: '📷' },
  { title: 'Close Protection Officer', salary: '£35,000 – £70,000+', category: 'security', icon: '🕵️' },
  { title: 'Control Room Operator', salary: '£24,000 – £32,000', category: 'security', icon: '🖥️' },
  { title: 'Mobile Security Patrol', salary: '£22,000 – £28,000', category: 'security', icon: '🚔' },
  { title: 'Security Manager', salary: '£35,000 – £55,000', category: 'security', icon: '📋' },
  { title: 'Bar Manager', salary: '£25,000 – £38,000', category: 'alcohol', icon: '🍺' },
  { title: 'Site Labourer', salary: '£22,000 – £30,000', category: 'construction', icon: '🔨' },
  { title: 'First Aid Trainer', salary: '£28,000 – £42,000', category: 'firstaid', icon: '🏥' },
]

export const TESTIMONIALS = [
  {
    name: 'Mohammed Ali',
    rating: 5,
    date: '2 weeks ago',
    text: 'Absolutely brilliant training! The instructors were knowledgeable and supportive. Passed my Door Supervisor exam first time and got a job within a week. SafeCert is the best!',
    course: 'Door Supervisor Training',
    verified: true,
  },
  {
    name: 'Sarah Johnson',
    rating: 5,
    date: '1 month ago',
    text: 'Excellent course, very well structured. The CCTV training was thorough and the staff were always available to answer questions. Highly recommend SafeCert to anyone looking to get into security.',
    course: 'CCTV Training',
    verified: true,
  },
  {
    name: 'David Okafor',
    rating: 5,
    date: '3 weeks ago',
    text: 'I did my Security Guard training here and it was fantastic. Professional environment, great trainers, and I felt fully prepared for my SIA exam. Got 100% pass!',
    course: 'Security Guard Training',
    verified: true,
  },
  {
    name: 'Priya Sharma',
    rating: 5,
    date: '2 months ago',
    text: 'The personal licence course was amazing. Covered everything I needed to know and the exam prep was spot on. Now running my own restaurant with full confidence.',
    course: 'Personal Licence (APLH)',
    verified: true,
  },
  {
    name: 'James Williams',
    rating: 5,
    date: '1 week ago',
    text: 'Top-up training for door supervisors was excellent. Quick, efficient, and covered all the updated legislation. Renewal done with zero stress. Will definitely return!',
    course: 'DS Top-Up Training',
    verified: true,
  },
  {
    name: 'Fatima Hassan',
    rating: 4,
    date: '3 months ago',
    text: 'Great first aid course, very hands-on and practical. The trainer made everything easy to understand. Certificate arrived quickly too. Would recommend SafeCert.',
    course: 'Emergency First Aid',
    verified: true,
  },
]

export const UK_LOCATIONS = [
  'London', 'Birmingham', 'Manchester', 'Leeds', 'Liverpool',
  'Sheffield', 'Bristol', 'Leicester', 'Coventry', 'Bradford',
  'Nottingham', 'Newcastle', 'Glasgow', 'Edinburgh', 'Cardiff',
  'Belfast', 'Southampton', 'Portsmouth', 'Reading', 'Oxford',
  'Cambridge', 'Brighton', 'Derby', 'Plymouth', 'Wolverhampton',
  'Swansea', 'Aberdeen', 'Dundee', 'Stoke-on-Trent', 'Preston',
]

export const STEPS = [
  {
    number: '01',
    title: 'Choose Your Course',
    description: 'Browse our wide range of accredited courses. Filter by category, location, or qualification level to find the right fit.',
    icon: '🎯',
  },
  {
    number: '02',
    title: 'Book & Pay Online',
    description: 'Secure your place with our easy online booking system. Flexible payment options including pay monthly available.',
    icon: '💳',
  },
  {
    number: '03',
    title: 'Attend Training',
    description: 'Train with our expert instructors at one of our 120+ UK locations or join our online courses from anywhere.',
    icon: '📚',
  },
  {
    number: '04',
    title: 'Get Certified',
    description: 'Pass your assessment and receive your nationally recognised qualification. We guide you through every step.',
    icon: '🏆',
  },
]
